apiVersion: apps/v1
kind: Deployment
metadata:
  name: config
  labels:
    app: config
spec:
  selector:
    matchLabels:
      app: config
  replicas: 1
  template:
    metadata:
      labels:
        app: config
    spec:
      containers:
        - name: config
          image: cmoragalaz/config:latest
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: config
  labels:
    app: config
spec:
  selector:
    app: config
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer